### PR TITLE
Code structure for benchmarking optimizers

### PR DESCRIPTION
**Pull request by fKunstner**
As discussed with @gowerrobert, proposal for a code structure to run benchmarks and save data from the runs.

[The readme](https://github.com/fKunstner/kmers/blob/c80c77189a5ec885b70131fa5a757ae4a13d2dda/solver_comparison/readme.md) has a short description of the code.

To run a test script, 
- create and source an environment file (see `Configuration` in the readme)
- install the library `pip install -e .` in the `solver_comparison` folder
- run `python scripts/make_experiments.py`

Currently only runs GD+LineSearch on the Logistic model on the test problem data, but other optimizers/problems should be easy to add.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
Thanks for making the changes, @fKunstner.  

This is a bit more Python than I feel comfortable reviewing, so hopefully @gowerrobert or @WardBrian can take a look.

One question I have is that this looks like it's setting up its own package.  What's the motivation for doing this rather than just including it as part of the existing package?

**Comment by WardBrian** [comment]
> One question I have is that this looks like it's setting up its own package. What's the motivation for doing this rather than just including it as part of the existing package?

I have the same question but the opposite instinct, which is more would this infrastructure be better served by living in a separate repo rather than this one?

I suppose it depends on if we intend this repo to serve as "the code for the paper" or "the home for a released library/tool". If its the former and we intend on making another repository later for anything releasable, this seems like a reasonable way to organize it.

**Comment by bob-carpenter** [comment]
I think those two things will be separate projects.

1.  research code for the paper
    a. data format parsers for reads and reference transcriptome
    b. multiple optimizer codes
    c. code for simulating test data both from the model and more realistically
    d. code for testing optimizers against data sets with known compositional basis (simulated data)
    e. code for testing optimizers against data sets with unknown truth (real data)
    f. code for running other systems like salmon and kallisto for comparison

2. production code for end users
    a. data format parser for reads and transcriptome
    a. our best choice of optimizer and tuning parameter knobs and levers to expose

The goal for (1) is to provide a way for researchers to reproduce our results, so it doesn't have to be super portable or robust.  The goal for (2) is to build stable and performant software for users.  When I said I wanted to be involved with design, I meant for (2).

**Comment by fKunstner** [comment]
Thanks for giving it a look!

> What's the motivation for doing this rather than just including it as part of the existing package?

Yes, it could also be a subpackage, I was aiming for minimal changes to the existing code.

After discussion @gowerrobert, assuming this is the repo for `1. research code for the paper`, it makes sense to have the optimization bits (`1.d./1.e.`) as a separate package. The "benchmarking optimization" is orthogonal to the scientific problem, and just needs to use `kmerexpr` to load problems. Of course `kmerexpr` eventually needs an optimizer, but the infrastructure for the comparisons seems less relevant.

> I have the same question but the opposite instinct, which is more would this infrastructure be better served by living in a separate repo rather than this one?

I'm open to move this code to another repo if you want minimal notifications.

@gowerrobert did I miss something?

**Comment by WardBrian** [comment]
Bob answered my question so I’m happy to have it here, I just wanted to check. Thanks!

**Comment by gowerrobert** [comment]
That was pretty much everything, thanks @fKunstner ! 

For now I like the organization of having this "solver_comparison" as a separate package. It allows us to mess around with lots of different experimental methods without messing with kmerexp. And even for the final 1. research code, I think it could make sense having solver_comparison as a separate package. Only other optimization researchers will care about what's in solver_comparison. Moreover, its sole purpose is for us to identify the best allround optimization method, which will then be implemented directly in kmerexp.

**Comment by gowerrobert** [comment]
So, let's go with solver_comparison being a separate sister package? I'm also fine with having it in the same package for now, if make initial development easier.

**Comment by fKunstner** [comment]
After discussion on Slack with @gowerrobert, we'll use a separate repo for the optimization comparison. Closing

**Pull request closed without merging**
