### PR TITLE
Fix installation issues

### PR DESCRIPTION
**Pull request by fKunstner**
Addresses issue https://github.com/bob-carpenter/kmers/issues/4 following @WardBrian's comments

- Changed `setup.cfg` to not use the `package_dir` and `where` parameters 
  - https://github.com/bob-carpenter/kmers/issues/4#issuecomment-1330730680 
  - https://github.com/bob-carpenter/kmers/issues/4#issuecomment-1331174369
- Added a test to import each file in kmerexpr (`test/test_imports.py`) 
- Fixed import statements for files in kmerexpr
- Modified script files to have a `if __name__ == "__main__"` guard to avoid side-effect on imports when running the test

### CODE REVIEW

**Comment by WardBrian** [comment]
Thanks for fixing up the setup.cfg and the imports!

> Added a test to import each file in kmerexpr (test/test_imports.py)

This won't be necessary if/when we actually have tests for each module

> Modified script files to have a if __name__ == "__main__" guard to avoid side-effect on imports when running the test

I don't think the files which end up being entirely wrapped in `__name__ == "__main__"` checks (e.g. `kmerexpr/benchmark_read_length.py`) need to be tested as imports, really, and those are really just scripts which belong in a folder outside `kmerexpr/` entirely

**Comment by WardBrian** [comment]
I'm not sure if either is necessary. My instinct is to make a `scripts/` folder at the top level alongside `kmerexpr/` and `tests/`, move stuff into there if it isn't something we want to import from other files, and get rid of `test_imports`

**Comment by fKunstner** [comment]
Bump - can this be merged?

**Comment by WardBrian** [comment]
My bad, thought it had been

**Pull request merged**
